AY2425S2-CS2103T-T08-1/tp

docs/team/clif.md
Add clif.md data.
This data is required for the webpage where
all team member's information a displayed.
I will be creating a pull request from this branch to the team's repo master and to wait for someone
to approve the pull request
=> Add clif's info

README.md, docs/_markbind/layouts/default.md
Readme file has been updated to be based on our
project requirement. This includes correct png image, correct hyperlinks and a badge pointing to our workflow
I have also updated the markbind page to have a github link pointing to our repository
=> Update readme and markbind

docs/AboutUs.md
Change the website to include siva's image and github information. This was originally missing which caused the github to not register it as done
=> Change website

docs/AboutUs.md
The name was not changed I have updated the
name of the website to be more correct again
=> Change details

src/main/java/seedu/address/logic/Messages.java
The delete command is already complete.
I merely edit some parts of the code that
leads to an incorrect format.
=> dit delete command

src/main/java/seedu/address/model/person/Person.java
- Ensure dish name is case insensitive
=> Debug addOrder Command

src/main/java/seedu/address/logic/commands/ViewOrdersCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/ViewOrdersCommandParser.java, src/test/java/seedu/address/logic/commands/ViewOrdersCommandTest.java
- Create ViewOrdersCommand.java and ViewOrdersCommandParser.java
- Modify AddressBookParser.java to include viewOrders command
- Add ViewOrdersCommandTest.java
=> Add viewOrders command

src/main/java/seedu/address/logic/commands/FindOrdersCommand.java, src/main/java/seedu/address/logic/parser/AddressBookParser.java, src/main/java/seedu/address/logic/parser/FindOrdersCommandParser.java, src/main/java/seedu/address/model/person/OrdersContainsKeywordsPredicate.java
- Create FindOrdersCommand.java and FindOrdersCommandParser.java
- Modify AddressBookParser.java to include command `findOrders`
- Create OrdersContainsKeywordsPredicate.java to filter order names that contains specific keywords
Closes #36
=> Add findOrders command

docs/UserGuide.md
Change the contents of the UG to be more
in line with the latest features in our code.
=> Change the UG

src/main/java/seedu/address/logic/commands/ViewOrdersCommand.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/ViewOrdersCommandTest.java, src/test/java/seedu/address/logic/parser/ViewOrdersCommandParserTest.java, src/test/java/seedu/address/testutil/TypicalPersons.java
- Fix equal method in ViewOrdersCommand.java
- Fix ViewOrdersCommandTest.java
- Add ViewOrderCommandParserTest.java
- Modify typicalPersonAddressBook.json and TypicalPersons.java to pass testcase
Closes #58
=> Debug and add tests for viewOrders

src/main/java/seedu/address/logic/commands/FindOrdersCommand.java, src/main/java/seedu/address/model/person/OrdersContainsKeywordsPredicate.java, src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json, src/test/java/seedu/address/logic/commands/FindOrdersCommandTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/TypicalPersons.java
- Add test for FindOrdersCommand
=> Debug and add tests for findOrders

src/test/java/seedu/address/logic/commands/FindOrdersCommandTest.java, src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
Fixed some errors regarding to the tests. I have also updated the test cases to ensure that they are working well enough.
=> Fx some errors

src/test/java/seedu/address/logic/commands/FindOrdersCommandTest.java, src/test/java/seedu/address/logic/parser/FindOrdersCommandParserTest.java, src/test/java/seedu/address/testutil/PersonBuilder.java
- Modifies the build function in PersonBuilder.java to include order history
- Improves the test cases in FindOrdersCommandTest.java
- Adds FindOrdersCommandParserTest.java to improve test coverage
=> Fix PersonBuilder.java and add tests to findOrders

docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/StorageClassDiagram.puml, docs/diagrams/UndoRedoState0.puml, docs/diagrams/UndoRedoState1.puml, docs/diagrams/UndoRedoState2.puml, docs/diagrams/UndoRedoState3.puml, docs/diagrams/UndoRedoState4.puml, docs/diagrams/UndoRedoState5.puml, docs/diagrams/UndoSequenceDiagram-Model.puml
Added more stuff to the UML diagram so they are clearer and more in line with our version
=> Improve the UML diagram

build.gradle
Add the add assertions command into the gradle file From now on assertions is enabled
=> Add enable assertions

docs/diagrams/BetterModelClassDiagram.puml, docs/diagrams/ModelClassDiagram.puml, docs/diagrams/StorageClassDiagram.puml, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Update model class diagrams
The model class diagrams are outdated and do not accurately reflect recent changes in the codebase, making them less useful for documentation and understanding the system design.
Update the model class diagrams to align with the latest implementation. Modify class relationships, attributes, and methods as needed to match the current structure.
This ensures that the documentation remains accurate and useful for developers working on the project. Keeping diagrams up to date helps with onboarding and system maintenance.
This change improves clarity and prevents confusion caused by outdated documentation.
=> update model class diagrams

docs/diagrams/addOrderSequenceDiagram.puml
Add a new UML sequence Diagram for addOrderCommand
=> Add UML Diagram

docs/UserGuide.md, src/main/java/seedu/address/logic/commands/AddCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- Fix UserGuide.md
- Fix AddCommand.java and AddCommandParser.java to save preferences
=> Fix add customer

docs/diagrams/ViewOrdersSequenceDiagram.puml, docs/diagrams/style.puml
=> Update UML diagram

src/main/java/seedu/address/ui/HelpWindow.java
=> Change url in help window

src/main/java/seedu/address/logic/commands/FindPreferencesCommand.java
=> Fix message usage in FindPreferencesCommand.java

docs/DeveloperGuide.md, docs/UserGuide.md, src/main/java/seedu/address/logic/commands/SavePreferenceCommand.java, src/main/java/seedu/address/logic/commands/TagCommand.java, src/main/java/seedu/address/model/person/Preference.java, src/test/java/seedu/address/logic/commands/SavePreferenceCommandTest.java
Edit code, UG and DG to fix bugs from PE-dry run
- update UI after savePreference
- prevent addition of repetitive tags
=> Update UG and DG
